---
# tasks file for nginx

- name: install nginx
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nginx

- name: create data dir
  command: mkdir -p /data/html

- name: nginx template        
  template: src=nginx.conf dest=/etc/nginx/ 
- name: www template
  template: src=www.conf dest=/etc/nginx/conf.d/
- name: php test page
  copy : src=index.php dest=/data/html/ 
- name: chown nginx
  command: chown -R nginx.nginx /data/html
