---
# tasks file for common

- name: Install epel
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - epel-release

- name: install libselinux-python
  yum:
    name: libselinux-python
    state: present
  tags:
    - optimize
    - selinux

- name: turn off selinux
  selinux:
    state: disabled
  register: se
  tags:
    - optimize
    - selinux

- name: Configure firewalld
  shell: systemctl stop firewalld
  ignore_errors: yes


